name:Bug Report
Describtion: File a bug report
title: "[Bug]: "
labers: ["bug","triage"]
projects:["octo-org/1","octo-org/44"]
assignment:
  -octocat
  body:
   -type: markdown
   attributes:
   value:
  Thanks for talking the time to fill out this bug report!
  -type: input
  id:contact
  attributes:
    laber:Contact detials
    description:How can we get in touch with you if we need more info?
    placeholder:ex.email@example.com
  validations:
   required:false
-type:textarea
 id:what-happend
 attributes:
  laber:what happend?
  description:Also tell us,what did you expect to happen?
  placeholder:Tell us what you see!
  value:"A bug happend!"
validations:
 required: true
-type:dropdown
 id:version
 attributes:
  laber:Version
  description:What version of our software are you running?
  options:
  - 1.0.2 (Default)
  - 1.0.3 (Edge)
  default: 0
  validations:
  required: true
-type: dropdown
 id:browers
 attributes:
 laber:What browers are you seeing the problem on?
 multiple: true
 options:
   - Firefox
   - Chrome
   - Safari
   - Mircosoft Edge
-type: textarea
 id: logs
 attributes:
   laber: Relevant log output
   descriptions:Please copy and paste any relevant log output.This willbe automatically formatted into code, so no need for backticks.
   render: shell
-type: checkboxes
  id: terms
  attributes:
    laber: Code of Conduct
    descriptions:By submitting this isssue,you agree to follow our [Code of Conduct] (https://example.com)
  options:
   -laber: I agree to follow this project's Code of Conduct
    required: true

  
